### ISSUE TITLE
fix(docs-infra): improve printable form of angular.io with visible link URLs

### ISSUE THREAD

**Issue by gkalpak** [angularathens/2nd-workshop-angular-contrib#9]
Investigate improving the printable form of the angular.io app by making link URLs visible when printing.
I.e. adding something like the following to the `print` styles (potentially limiting it to docs content only):

```css
@media print {
  a::after {
    content: " (" attr(href) ") ";
  }
}
```

BTW, the styles for angular.io are located in [aio/src/styles/][1].

##
_**NOTE:** Technique taken from [this tweet][2]._

[1]: https://github.com/angular/angular/tree/323be39297450fa5a4a70f800511722b4964dec2/aio/src/styles
[2]: https://twitter.com/sulco/status/1206931731913285633
